### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by LunaUrsa** [TripSit/mobile#7]
If you don't have internet and load up the app, nothing will be displayed. If you later connect to the internet, you need to force-close the app and restart it, in order for drugs to appear. 

The app should come pre-loaded with drug data by default, and then when you load up the app/get internet connection it should refresh the data (https://github.com/tripsit/drugs) and store it on the phone

This way, if they're at a festival or otherwise without internet, they can still see information

**Comment by sympact06** [comment]
This feature has a high priority impact and will be done first.
